-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 21:11:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bxb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bxb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bxb` DEFAULT CHARACTER SET latin1 ;
USE `bxb` ;

-- -----------------------------------------------------
-- Table `bxb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`client` ;

CREATE TABLE IF NOT EXISTS `bxb`.`client` (
  `clientno` INT(11) NOT NULL,
  `first_name` CHAR(20) NOT NULL,
  `last_name` CHAR(15) NOT NULL,
  `birthdate` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `contactNo` VARCHAR(15) NOT NULL,
  `accountcreated` TIMESTAMP(2) NOT NULL,
  `accepted` ENUM('Y', 'N') NOT NULL,
  `profpic` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`clientno`),
  UNIQUE INDEX `clientNo_UNIQUE` (`clientno` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bxb`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`service` ;

CREATE TABLE IF NOT EXISTS `bxb`.`service` (
  `serviceid` INT(11) NOT NULL,
  `servicename` CHAR(20) NOT NULL,
  `serviceamount` FLOAT NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`serviceid`),
  UNIQUE INDEX `ServiceId_UNIQUE` (`serviceid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bxb`.`serviceprovider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`serviceprovider` ;

CREATE TABLE IF NOT EXISTS `bxb`.`serviceprovider` (
  `spid` INT(11) NOT NULL,
  `first_name` CHAR(20) NOT NULL,
  `last_name` CHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contactno` INT(15) NOT NULL,
  `totalrating` FLOAT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `accepted` ENUM('Y', 'N') NOT NULL,
  `profpic` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`spid`),
  UNIQUE INDEX `spID_UNIQUE` (`spid` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bxb`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`appointment` ;

CREATE TABLE IF NOT EXISTS `bxb`.`appointment` (
  `appointmentno` INT(11) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `daterequest` DATE NOT NULL,
  `dateofservice` DATE NOT NULL,
  `dateFinished` DATE NOT NULL,
  `status` CHAR(10) NOT NULL,
  `clientno` INT(11) NOT NULL,
  `spid` INT(11) NOT NULL,
  `serviceid` INT(11) NOT NULL,
  PRIMARY KEY (`appointmentno`),
  UNIQUE INDEX `appointmentNo_UNIQUE` (`appointmentno` ASC),
  INDEX `clientNo_idx` (`clientno` ASC),
  INDEX `spID_idx` (`spid` ASC),
  INDEX `serviceID_idx` (`serviceid` ASC),
  CONSTRAINT `fk_clientno_clientno`
    FOREIGN KEY (`clientno`)
    REFERENCES `bxb`.`client` (`clientno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_serviceid_serviceid`
    FOREIGN KEY (`serviceid`)
    REFERENCES `bxb`.`service` (`serviceid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spid_spid`
    FOREIGN KEY (`spid`)
    REFERENCES `bxb`.`serviceprovider` (`spid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bxb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`messages` ;

CREATE TABLE IF NOT EXISTS `bxb`.`messages` (
  `messageid` VARCHAR(45) NOT NULL,
  `reciever` INT(11) NOT NULL,
  `sender` INT(11) NOT NULL,
  `mdesc` VARCHAR(160) NULL DEFAULT NULL,
  PRIMARY KEY (`messageid`),
  INDEX `fk_sender_clientno_idx` (`sender` ASC),
  INDEX `fk_reciever_spid` (`reciever` ASC),
  CONSTRAINT `fk_reciever_clientno`
    FOREIGN KEY (`reciever`)
    REFERENCES `bxb`.`client` (`clientno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reciever_spid`
    FOREIGN KEY (`reciever`)
    REFERENCES `bxb`.`serviceprovider` (`spid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sender_clientno`
    FOREIGN KEY (`sender`)
    REFERENCES `bxb`.`client` (`clientno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sender_spid`
    FOREIGN KEY (`sender`)
    REFERENCES `bxb`.`serviceprovider` (`spid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bxb`.`spservice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`spservice` ;

CREATE TABLE IF NOT EXISTS `bxb`.`spservice` (
  `spid` INT(11) NOT NULL,
  `serviceid` INT(11) NOT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  INDEX `serviceID_idx` (`serviceid` ASC),
  INDEX `spID_idx` (`spid` ASC),
  CONSTRAINT `fk_serviceid_serviceidsp`
    FOREIGN KEY (`serviceid`)
    REFERENCES `bxb`.`service` (`serviceid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spid_spidsp`
    FOREIGN KEY (`spid`)
    REFERENCES `bxb`.`serviceprovider` (`spid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bxb`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bxb`.`transaction` ;

CREATE TABLE IF NOT EXISTS `bxb`.`transaction` (
  `idtransaction` INT(11) NOT NULL,
  `transdate` TIMESTAMP(2) NOT NULL,
  `appointmentno` INT(11) NOT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `fk_appointmentNo_appointmentNo_idx` (`appointmentno` ASC),
  CONSTRAINT `fk_appointmentNo_appointmentNo`
    FOREIGN KEY (`appointmentno`)
    REFERENCES `bxb`.`appointment` (`appointmentno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
